### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jojoli123** [c0ny1/chunked-coding-converter#7]
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at burp.a3_.a(Unknown Source)
	at burp.a3_.<init>(Unknown Source)
	at burp.gcg.a(Unknown Source)
	at burp.ao3.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

**Comment by c0ny1** [comment]
使用jd-gui反编译jar，看有没有burp.BurpExtender类。

**Comment by mKeySafe** [comment]
使用延时分块功能时报错
java.lang.NullPointerException: Cannot invoke "burp.sleepchunked.SleepChunkedWorker.cancel(boolean)" because the return value of "burp.sleepchunked.SleepChunkedDlg.access$200(burp.sleepchunked.SleepChunkedDlg)" is null
	at burp.sleepchunked.SleepChunkedDlg$1.actionPerformed(SleepChunkedDlg.java:175)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
